import {
  Meeting,
  UserTask,
  AnalyticsSummary,
  User,
  IntegrationStatus,
} from '../types';

const today = new Date();
const todayStr = today.toISOString().split('T')[0];

export const demoUser: User = {
  id: 'user-rahul-sharma',
  email: 'rahul.sharma@meetingflow.io',
  name: 'Rahul Sharma',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const demoUpcomingMeetings: Meeting[] = [
  {
    id: 'meet-up-1',
    googleEventId: 'gcal-evt-101',
    meetCode: 'abc-defg-hij',
    meetUrl: 'https://meet.google.com/abc-defg-hij',
    title: 'Product Strategy & Q4 Roadmap Review',
    description: 'Review quarterly goals, enterprise client feedback, and sprint prioritization.',
    startTime: `${todayStr}T10:00:00.000Z`,
    endTime: `${todayStr}T11:00:00.000Z`,
    durationMinutes: 60,
    status: 'SCHEDULED',
    organizerId: demoUser.id,
    organizerName: demoUser.name,
    organizerEmail: demoUser.email,
    participants: [
      { id: 'p1', meetingId: 'meet-up-1', name: 'Rahul Sharma', email: 'rahul.sharma@meetingflow.io', role: 'organizer' },
      { id: 'p2', meetingId: 'meet-up-1', name: 'Arpita Sen', email: 'arpita.sen@meetingflow.io', role: 'attendee' },
      { id: 'p3', meetingId: 'meet-up-1', name: 'Ananya Roy', email: 'ananya.roy@meetingflow.io', role: 'attendee' },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'meet-up-2',
    googleEventId: 'gcal-evt-102',
    meetCode: 'mno-pqrs-tuv',
    meetUrl: 'https://meet.google.com/mno-pqrs-tuv',
    title: 'Frontend Architecture & Design System Sync',
    description: 'Aligning React 19 component library, Tailwind tokens, and accessibility standards.',
    startTime: `${todayStr}T11:30:00.000Z`,
    endTime: `${todayStr}T12:15:00.000Z`,
    durationMinutes: 45,
    status: 'SCHEDULED',
    organizerId: 'user-arpita-sen',
    organizerName: 'Arpita Sen',
    organizerEmail: 'arpita.sen@meetingflow.io',
    participants: [
      { id: 'p6', meetingId: 'meet-up-2', name: 'Arpita Sen', email: 'arpita.sen@meetingflow.io', role: 'organizer' },
      { id: 'p7', meetingId: 'meet-up-2', name: 'Rahul Sharma', email: 'rahul.sharma@meetingflow.io', role: 'attendee' },
    ],
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'meet-up-3',
    googleEventId: 'gcal-evt-103',
    meetCode: 'wxy-zabc-def',
    meetUrl: 'https://meet.google.com/wxy-zabc-def',
    title: 'Client Onboarding & Enterprise Integration Kickoff',
    description: 'Technical walkthrough of SSO, SCIM provisioning, and data export endpoints with Acme Corp.',
    startTime: `${todayStr}T14:00:00.000Z`,
    endTime: `${todayStr}T15:00:00.000Z`,
    durationMinutes: 60,
    status: 'SCHEDULED',
    organizerId: 'user-ananya-roy',
    organizerName: 'Ananya Roy',
    organizerEmail: 'ananya.roy@meetingflow.io',
    participants: [
      { id: 'p9', meetingId: 'meet-up-3', name: 'Ananya Roy', email: 'ananya.roy@meetingflow.io', role: 'organizer' },
      { id: 'p10', meetingId: 'meet-up-3', name: 'Rahul Sharma', email: 'rahul.sharma@meetingflow.io', role: 'attendee' },
    ],
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    updatedAt: new Date(Date.now() - 21600000).toISOString(),
  },
];

export const demoCompletedMeetings: Meeting[] = [
  {
    id: 'meet-comp-1',
    googleEventId: 'gcal-evt-comp-01',
    meetCode: 'deb-rief-q03',
    meetUrl: 'https://meet.google.com/deb-rief-q03',
    title: 'Q3 Growth Debrief & Conversion Optimization',
    description: 'Review Q3 marketing metrics, sign-up funnels, and enterprise sales conversions.',
    startTime: new Date(Date.now() - 172800000).toISOString(),
    endTime: new Date(Date.now() - 169200000).toISOString(),
    durationMinutes: 60,
    status: 'COMPLETED',
    organizerId: demoUser.id,
    organizerName: demoUser.name,
    organizerEmail: demoUser.email,
    participants: [
      { id: 'cp1', meetingId: 'meet-comp-1', name: 'Rahul Sharma', email: 'rahul.sharma@meetingflow.io', role: 'organizer' },
      { id: 'cp2', meetingId: 'meet-comp-1', name: 'Arpita Sen', email: 'arpita.sen@meetingflow.io', role: 'attendee' },
      { id: 'cp3', meetingId: 'meet-comp-1', name: 'Ananya Roy', email: 'ananya.roy@meetingflow.io', role: 'attendee' },
    ],
    transcripts: [
      { id: 't1', meetingId: 'meet-comp-1', sequence: 1, speaker: 'Rahul', timestamp: '10:02', text: 'Good morning everyone. Let\'s debrief the Q3 launch numbers and tackle our marketing backlog.' },
      { id: 't2', meetingId: 'meet-comp-1', sequence: 2, speaker: 'Arpita', timestamp: '10:05', text: 'Overall signups grew by 38%, but onboarding drop-off is concentrated on the OAuth verification screen.' },
      { id: 't3', meetingId: 'meet-comp-1', sequence: 3, speaker: 'Rahul', timestamp: '10:14', text: 'Agreed. Rahul will finalize the campaign creative and copy revisions by Friday.' },
      { id: 't4', meetingId: 'meet-comp-1', sequence: 4, speaker: 'Arpita', timestamp: '10:16', text: 'I will prepare the revised enterprise client proposal and send it out.' },
    ],
    summary: 'The team reviewed Q3 launch metrics, noting 38% user growth alongside onboarding friction during OAuth verification. Deliverables were assigned with firm dates.',
    keyDiscussions: [
      '38% quarter-over-quarter signup expansion following the product announcement.',
      'Onboarding funnel drop-off identified around Google OAuth token verification latency.',
      'Enterprise pricing and competitor tier adjustments.'
    ],
    decisions: [
      { id: 'd1', meetingId: 'meet-comp-1', decision: 'Cache Google OAuth token validation responses to eliminate onboarding drop-off.', context: 'Identified as main source of latency.', timestamp: '10:09', createdAt: new Date().toISOString() },
    ],
    actionItems: [
      {
        id: 'act-1',
        meetingId: 'meet-comp-1',
        task: 'Finalize campaign creative and copy revisions',
        ownerName: 'Rahul Sharma',
        ownerEmail: 'rahul.sharma@meetingflow.io',
        dueDate: todayStr,
        priority: 'HIGH',
        status: 'PENDING',
        confidence: 'high',
        sourceTimestamp: '10:14',
        jiraIssueKey: 'MF-101',
        jiraIssueUrl: 'https://jira.atlassian.net/browse/MF-101',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'act-2',
        meetingId: 'meet-comp-1',
        task: 'Prepare revised enterprise client proposal',
        ownerName: 'Arpita Sen',
        ownerEmail: 'arpita.sen@meetingflow.io',
        dueDate: null,
        priority: 'HIGH',
        status: 'PENDING',
        confidence: 'high',
        sourceTimestamp: '10:16',
        jiraIssueKey: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 169200000).toISOString(),
  },
];

export const demoTasks: UserTask[] = [
  {
    id: 'task-1',
    userId: demoUser.id,
    actionItemId: 'act-1',
    title: 'Finalize campaign creative and copy revisions',
    meetingId: 'meet-comp-1',
    meetingTitle: 'Q3 Growth Debrief & Conversion Optimization',
    dueDate: todayStr,
    priority: 'HIGH',
    status: 'PENDING',
    jiraIssueKey: 'MF-101',
    reminderAt: null,
    completedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    userId: demoUser.id,
    actionItemId: 'act-2',
    title: 'Prepare revised enterprise client proposal',
    meetingId: 'meet-comp-1',
    meetingTitle: 'Q3 Growth Debrief & Conversion Optimization',
    dueDate: null,
    priority: 'MEDIUM',
    status: 'PENDING',
    jiraIssueKey: null,
    reminderAt: null,
    completedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoAnalytics: AnalyticsSummary = {
  totalMeetings: 8,
  meetingHours: {
    today: 2.2,
    thisWeek: 7.5,
    thisMonth: 28.0,
    averageDuration: 52,
  },
  tasks: {
    total: 14,
    completed: 9,
    pending: 5,
    overdue: 1,
    myOpenTasks: 2,
  },
  dailyHoursBreakdown: [
    { day: 'Mon', hours: 2.5, meetingCount: 3 },
    { day: 'Tue', hours: 1.5, meetingCount: 2 },
    { day: 'Wed', hours: 3.0, meetingCount: 4 },
    { day: 'Thu', hours: 2.0, meetingCount: 2 },
    { day: 'Fri', hours: 1.0, meetingCount: 1 },
  ],
  tasksByPriority: [
    { priority: 'HIGH', count: 4 },
    { priority: 'MEDIUM', count: 7 },
    { priority: 'LOW', count: 3 },
  ],
  meetingsByStatus: [
    { status: 'SCHEDULED', count: 3 },
    { status: 'COMPLETED', count: 5 },
  ],
};

export const demoIntegrationStatus: IntegrationStatus = {
  google: {
    isConnected: true,
    isConfigured: true,
    calendarConnected: true,
    meetConnected: true,
    authUrl: '',
  },
  jira: {
    isConnected: true,
    isConfigured: true,
    siteName: 'MeetingFlow Jira',
    siteUrl: 'https://meetingflow.atlassian.net',
    accountEmail: 'rahul.sharma@meetingflow.io',
    defaultProject: 'MF',
    isOAuthConfigured: true,
  },
  gemini: {
    isConfigured: true,
    model: 'gemini-2.5-flash',
    aiAnalysisEnabled: true,
  },
};
